In [1]:
import pandas as pd
import json

In [2]:
# 총 100개의 test 표본에서 NER 생성 결과를 불러옴
results = pd.read_csv('/workspace/datas/generated/flan-t5-base_fewnerd-tuned_fewnerd_small.csv')

results = results[:100]

results.head()

,Sentence,NER,generated_ner
0,In the early 1930s the band moved to the Grill...,"{""building-other"": [""Grill Room""], ""building-h...","{ ""building-hotel"": [""Grill Room of the Taft H..."
1,The final season of minor league play Elkin Me...,"{""location-park"": [""Elkin Memorial Park""]}","{ ""location-park"": [""Elkin Memorial Park""]}"
2,"They finished the season 14–19 , 9–9 in C-USA ...","{""event-sportsevent"": [""C-USA play""]}","{ ""organization-sportsleague"": [""C-USA""]}"
3,"The B-52 pilot , Major Larry G. Messinger , la...","{""product-other"": [""B-52""], ""person-other"": [""...","{ ""product-airplane"": [""B-52""], ""person-soldie..."
4,The Austro-Hungarian Navy built and operated t...,"{""organization-other"": [""Austro-Hungarian Navy""]}","{ ""organization-other"": [""Austro-Hungarian Nav..."

In [4]:
count_dict = dict()

for ner_json in results['NER']:
    json_dict = json.loads(ner_json)
    for entity, values in json_dict.items():
        entity = entity.split('-')[0]
        if entity not in count_dict:
            count_dict[entity] = len(values)
        else:
            count_dict[entity] += len(values)

print(count_dict)

{'building': 7, 'location': 68, 'organization': 62, 'event': 11, 'product': 19, 'person': 48, 'other': 19, 'art': 12}

# flan-t5-large 결과 분석

일단 현재 overfitting하는 경향이 나타났고, weight decay 수치를 높여봐도 오히려 못하는 상황

In [2]:
results = pd.read_csv('/workspace/datas/generated/flan-t5-large-ner-json-conll2003_random-fp32-w1e3-lr4e5-full-promp1-tuned-conll2003.csv')

results.head()

,Sentence,NER,types,generated_ner
0,"SOCCER - JAPAN GET LUCKY WIN , CHINA IN SURPRI...","{""LOC"": [""JAPAN""], ""PER"": [""CHINA""]}",conll2003,"""LOC"": [""JAPAN"", ""CHINA""]"
1,Nadim Ladki,"{""PER"": [""Nadim Ladki""]}",conll2003,"""PER"": [""Nadim Ladki""]"
2,"AL-AIN , United Arab Emirates 1996-12-06","{""LOC"": [""AL-AIN"", ""United Arab Emirates""]}",conll2003,"""LOC"": [""AL-AIN"", ""United Arab Emirates""]"
3,Japan began the defence of their Asian Cup tit...,"{""LOC"": [""Japan"", ""Syria""], ""MISC"": [""Asian Cu...",conll2003,"""LOC"": [""Japan"", ""Syria""], ""MISC"": [""Asian Cup""]"
4,But China saw their luck desert them in the se...,"{""LOC"": [""China"", ""Uzbekistan""]}",conll2003,"""LOC"": [""China"", ""Uzbekistan""]"

In [3]:
def parse_json(json_str):
    try:
        # json 문자열 전처리
        if pd.isna(json_str):
            json_str = ""
        if len(json_str) == 0 or json_str[0] != '{':
            json_str = '{' + json_str + '}'
        
        json_obj = json.loads(json_str)
        return json_obj
    except (json.JSONDecodeError, TypeError):
        return None

In [ ]:
wrong_indices = []
for index, row in results.iterrows():
    ref_json = parse_json(row["NER"])
    pred_json = parse_json(row["generated_ner"])
    
    if str(ref_json) != str(pred_json):
        wrong_indices.append(index)

        print(f"Index {index}: Wrong")

Index 0: Match
Index 12: Match
Index 15: Match
Index 20: Match
Index 25: Match
Index 29: Match
Index 34: Match
Index 39: Match
Index 41: Match
Index 48: Match
Index 49: Match
Index 51: Match
Index 87: Match
Index 145: Match
Index 149: Match
Index 151: Match
Index 152: Match
Index 153: Match
Index 155: Match
Index 157: Match
Index 159: Match
Index 163: Match
Index 165: Match
Index 185: Match
Index 189: Match
Index 199: Match
Index 207: Match
Index 210: Match
Index 212: Match
Index 217: Match
Index 234: Match
Index 235: Match
Index 237: Match
Index 263: Match
Index 305: Match
Index 308: Match
Index 312: Match
Index 314: Match
Index 315: Match
Index 317: Match
Index 334: Match
Index 336: Match
Index 339: Match
Index 341: Match
Index 369: Match
Index 371: Match
Index 374: Match
Index 376: Match
Index 378: Match
Index 379: Match
Index 381: Match
Index 382: Match
Index 390: Match
Index 399: Match
Index 408: Match
Index 426: Match
Index 429: Match
Index 431: Match
Index 432: Match
Index 439: Match
Index 441: Match
Index 444: Match
Index 446: Match
Index 447: Match
Index 452: Match
Index 453: Match
Index 455: Match
Index 457: Match
Index 459: Match
Index 462: Match
Index 463: Match
Index 472: Match
Index 482: Match
Index 483: Match
Index 492: Match
Index 499: Match
Index 505: Match
Index 512: Match
Index 514: Match
Index 517: Match
Index 518: Match
Index 525: Match
Index 526: Match
Index 532: Match
Index 534: Match
Index 539: Match
Index 540: Match
Index 547: Match
Index 549: Match
Index 554: Match
Index 580: Match
Index 582: Match
Index 583: Match
Index 586: Match
Index 588: Match
Index 592: Match
Index 637: Match
Index 638: Match
Index 668: Match
Index 709: Match
Index 715: Match
Index 727: Match
Index 729: Match
Index 734: Match
Index 735: Match
Index 736: Match
Index 737: Match
Index 741: Match
Index 763: Match
Index 779: Match
Index 784: Match
Index 786: Match
Index 800: Match
Index 825: Match
Index 835: Match
Index 841: Match
Index 843: Match
Index 857: Match
Index 865: Match
Index 870: Match
Index 871: Match
Index 873: Match
Index 876: Match
Index 881: Match
Index 883: Match
Index 886: Match
Index 888: Match
Index 890: Match
Index 894: Match
Index 911: Match
Index 927: Match
Index 928: Match
Index 935: Match
Index 937: Match
Index 939: Match
Index 940: Match
Index 942: Match
Index 951: Match
Index 953: Match
Index 955: Match
Index 960: Match
Index 961: Match
Index 962: Match
Index 963: Match
Index 964: Match
Index 971: Match
Index 972: Match
Index 974: Match
Index 975: Match
Index 976: Match
Index 985: Match
Index 988: Match
Index 990: Match
Index 1000: Match
Index 1008: Match
Index 1012: Match
Index 1016: Match
Index 1018: Match
Index 1020: Match
Index 1021: Match
Index 1027: Match
Index 1038: Match
Index 1045: Match
Index 1048: Match
Index 1056: Match
Index 1065: Match
Index 1070: Match
Index 1071: Match
Index 1075: Match
Index 1081: Match
Index 1083: Match
Index 1086: Match
Index 1088: Match
Index 1095: Match
Index 1098: Match
Index 1100: Match
Index 1117: Match
Index 1130: Match
Index 1132: Match
Index 1164: Match
Index 1166: Match
Index 1167: Match
Index 1169: Match
Index 1171: Match
Index 1173: Match
Index 1174: Match
Index 1176: Match
Index 1178: Match
Index 1179: Match
Index 1189: Match
Index 1190: Match
Index 1195: Match
Index 1196: Match
Index 1197: Match
Index 1201: Match
Index 1202: Match
Index 1204: Match
Index 1205: Match
Index 1206: Match
Index 1209: Match
Index 1230: Match
Index 1232: Match
Index 1233: Match
Index 1236: Match
Index 1237: Match
Index 1242: Match
Index 1245: Match
Index 1246: Match
Index 1248: Match
Index 1254: Match
Index 1265: Match
Index 1276: Match
Index 1291: Match
Index 1292: Match
Index 1311: Match
Index 1315: Match
Index 1333: Match
Index 1336: Match
Index 1337: Match
Index 1341: Match
Index 1358: Match
Index 1380: Match
Index 1382: Match
Index 1391: Match
Index 1395: Match
Index 1403: Match
Index 1407: Match
Index 1408: Match
Index 1410: Match
Index 1436: Match
Index 1463: Match
Index 1470: Match
Index 1486: Match
Index 1490: Match
Index 1494: Match
Index 1519: Match
Index 1524: Match
Index 1527: Match
Index 1530: Match
Index 1531: Match
Index 1532: Match
Index 1535: Match
Index 1548: Match
Index 1562: Match
Index 1563: Match
Index 1569: Match
Index 1578: Match
Index 1584: Match
Index 1587: Match
Index 1601: Match
Index 1612: Match
Index 1641: Match
Index 1642: Match
Index 1644: Match
Index 1648: Match
Index 1656: Match
Index 1674: Match
Index 1678: Match
Index 1682: Match
Index 1683: Match
Index 1694: Match
Index 1704: Match
Index 1726: Match
Index 1773: Match
Index 1775: Match
Index 1777: Match
Index 1783: Match
Index 1791: Match
Index 1794: Match
Index 1804: Match
Index 1815: Match
Index 1817: Match
Index 1823: Match
Index 1829: Match
Index 1831: Match
Index 1833: Match
Index 1842: Match
Index 1843: Match
Index 1844: Match
Index 1853: Match
Index 1855: Match
Index 1866: Match
Index 1867: Match
Index 1868: Match
Index 1869: Match
Index 1870: Match
Index 1874: Match
Index 1880: Match
Index 1887: Match
Index 1890: Match
Index 1895: Match
Index 1897: Match
Index 1903: Match
Index 1919: Match
Index 1922: Match
Index 1929: Match
Index 1930: Match
Index 1937: Match
Index 1966: Match
Index 1967: Match
Index 1979: Match
Index 1985: Match
Index 1988: Match
Index 1991: Match
Index 1993: Match
Index 1996: Match
Index 2004: Match
Index 2007: Match
Index 2012: Match
Index 2017: Match
Index 2022: Match
Index 2034: Match
Index 2036: Match
Index 2042: Match
Index 2043: Match
Index 2044: Match
Index 2048: Match
Index 2049: Match
Index 2077: Match
Index 2080: Match
Index 2093: Match
Index 2095: Match
Index 2103: Match
Index 2114: Match
Index 2115: Match
Index 2139: Match
Index 2155: Match
Index 2184: Match
Index 2185: Match
Index 2188: Match
Index 2191: Match
Index 2206: Match
Index 2207: Match
Index 2211: Match
Index 2228: Match
Index 2234: Match
Index 2244: Match
Index 2248: Match
Index 2255: Match
Index 2256: Match
Index 2262: Match
Index 2275: Match
Index 2277: Match
Index 2279: Match
Index 2283: Match
Index 2284: Match
Index 2285: Match
Index 2286: Match
Index 2288: Match
Index 2290: Match
Index 2303: Match
Index 2307: Match
Index 2309: Match
Index 2316: Match
Index 2324: Match
Index 2343: Match
Index 2345: Match
Index 2350: Match
Index 2352: Match
Index 2355: Match
Index 2360: Match
Index 2361: Match
Index 2362: Match
Index 2363: Match
Index 2367: Match
Index 2377: Match
Index 2381: Match
Index 2394: Match
Index 2397: Match
Index 2402: Match
Index 2409: Match
Index 2412: Match
Index 2416: Match
Index 2419: Match
Index 2423: Match
Index 2433: Match
Index 2435: Match
Index 2436: Match
Index 2437: Match
Index 2438: Match
Index 2439: Match
Index 2441: Match
Index 2442: Match
Index 2443: Match
Index 2444: Match
Index 2445: Match
Index 2446: Match
Index 2447: Match
Index 2466: Match
Index 2490: Match
Index 2491: Match
Index 2493: Match
Index 2496: Match
Index 2497: Match
Index 2500: Match
Index 2506: Match
Index 2508: Match
Index 2511: Match
Index 2512: Match
Index 2515: Match
Index 2525: Match
Index 2528: Match
Index 2533: Match
Index 2539: Match
Index 2552: Match
Index 2554: Match
Index 2559: Match
Index 2560: Match
Index 2561: Match
Index 2562: Match
Index 2563: Match
Index 2567: Match
Index 2574: Match
Index 2576: Match
Index 2587: Match
Index 2612: Match
Index 2614: Match
Index 2621: Match
Index 2623: Match
Index 2626: Match
Index 2632: Match
Index 2633: Match
Index 2637: Match
Index 2645: Match
Index 2648: Match
Index 2650: Match
Index 2651: Match
Index 2652: Match
Index 2673: Match
Index 2676: Match
Index 2688: Match
Index 2728: Match
Index 2729: Match
Index 2746: Match
Index 2752: Match
Index 2764: Match
Index 2769: Match
Index 2778: Match
Index 2786: Match
Index 2788: Match
Index 2806: Match
Index 2808: Match
Index 2810: Match
Index 2812: Match
Index 2814: Match
Index 2816: Match
Index 2818: Match
Index 2820: Match
Index 2825: Match
Index 2826: Match
Index 2838: Match
Index 2847: Match
Index 2901: Match
Index 2914: Match
Index 2922: Match
Index 2942: Match
Index 2970: Match
Index 2973: Match
Index 2981: Match
Index 2990: Match
Index 2992: Match
Index 2994: Match
Index 2995: Match
Index 2997: Match
Index 2998: Match
Index 3019: Match
Index 3038: Match
Index 3043: Match
Index 3058: Match
Index 3061: Match
Index 3064: Match
Index 3076: Match
Index 3094: Match
Index 3115: Match
Index 3175: Match
Index 3184: Match
Index 3193: Match
Index 3251: Match
Index 3272: Match
Index 3273: Match
Index 3333: Match
Index 3335: Match
Index 3341: Match
Index 3348: Match
Index 3356: Match
Index 3375: Match
Index 3376: Match
Index 3377: Match
Index 3389: Match
Index 3390: Match
Index 3391: Match
Index 3392: Match
Index 3396: Match
Index 3398: Match
Index 3400: Match
Index 3401: Match
Index 3410: Match
Index 3413: Match
Index 3415: Match
Index 3442: Match
Index 3452: Match
Index 3466: Match
Index 3470: Match
Index 3472: Match
Index 3475: Match
Index 3476: Match
Index 3495: Match
Index 3496: Match
Index 3505: Match
Index 3512: Match
Index 3525: Match
Index 3527: Match
Index 3528: Match
Index 3532: Match
Index 3539: Match
Index 3541: Match
Index 3542: Match
Index 3544: Match
Index 3545: Match
Index 3553: Match
Index 3562: Match
Index 3563: Match
Index 3571: Match
Index 3592: Match
Index 3594: Match
Index 3595: Match
Index 3600: Match
Index 3601: Match
Index 3602: Match
Index 3604: Match
Index 3606: Match
Index 3613: Match
Index 3624: Match
Index 3626: Match
Index 3628: Match
Index 3630: Match
Index 3632: Match
Index 3638: Match
Index 3639: Match
Index 3664: Match
Index 3675: Match
Index 3680: Match
Index 3682: Match

In [7]:
wrong_df = results.loc[wrong_indices]

In [9]:
print(len(wrong_df))

543

In [8]:
wrong_df.sample(10)

,Sentence,NER,types,generated_ner
3525,NBA BASKETBALL - FRIDAY 'S RESULTS .,"{""ORG"": [""NBA""]}",conll2003,"""MISC"": [""NBA""]"
955,"Czech ambassador to the United Nations , Karel...","{""LOC"": [""Czech""], ""ORG"": [""United Nations"", ""...",conll2003,"""MISC"": [""Czech"", ""Czechs""], ""PER"": [""Karel Ko..."
1088,Mediterranean oil products were steady to most...,"{""ORG"": [""Elf""]}",conll2003,"""MISC"": [""Mediterranean""], ""ORG"": [""Elf""]"
1897,"Toledo 61,514 0","{""LOC"": [""Toledo""]}",conll2003,"""ORG"": [""Toledo""]"
153,"FIFA 's players ' status committee , meeting i...","{""ORG"": [""FIFA"", ""Udinese""], ""LOC"": [""Barcelon...",conll2003,"""ORG"": [""FIFA""], ""LOC"": [""Barcelona""], ""MISC"":..."
49,"Syria : 24 - Salem Bitar , 3 - Bachar Srour ; ...","{""LOC"": [""Syria""], ""PER"": [""Salem Bitar"", ""Bac...",conll2003,"""LOC"": [""Syria""], ""PER"": [""Salem Bitar"", ""Bach..."
3272,Postponed : Airdrieonians v Clydebank ( to Wed...,"{""ORG"": [""Airdrieonians"", ""Clydebank"", ""East""]}",conll2003,"""ORG"": [""Airdrieonians"", ""Clydebank""], ""LOC"": ..."
871,Bottom team Reggiana are also without a suspen...,"{""ORG"": [""Reggiana""], ""MISC"": [""German""], ""PER...",conll2003,"""ORG"": [""Reggiana""], ""PER"": [""Dietmar Beiersdo..."
1880,U.S. barge rates were lightly quoted Friday on...,"{""LOC"": [""U.S."", ""St. Louis""]}",conll2003,"""LOC"": [""U.S.""], ""ORG"": [""St. Louis Merchants ..."
1071,Trade and Industry Secretary Ian Lang added th...,"{""ORG"": [""Trade and Industry""], ""PER"": [""Ian L...",conll2003,"""PER"": [""Ian Lang""], ""LOC"": [""Britain"", ""Unite..."

# classification inference 결과 살펴보기

In [1]:
import numpy as np
import os
import pandas as pd

In [24]:
result_dir_path = "/workspace/datas/encoder_result/conll2003/flan-t5-base-encoder-switch-ner-custom-class_weight-drop10-smoothing0-cycle10-lr2e-4-cosine_restart"
dataset_csv_path = "/workspace/datas/conll2003/testb.switch.csv"

dataset_df = pd.read_csv(dataset_csv_path)
test_texts = dataset_df['Sentence'].tolist()

labels = np.load(os.path.join(result_dir_path, "test_labels.npy"))
predictions = np.load(os.path.join(result_dir_path, "test_predictions.npy"))

In [14]:
print(predictions.shape)
print(labels.shape)

(14732, 223, 2)
(14732, 223)

In [15]:
predictions_oh = predictions.argmax(axis=2)
print(predictions_oh[1])

[0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]

In [17]:
print(labels[1])

[-100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100
 -100 -100 -100 -100 -100 -100    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0 -100 -100 -100 -100 -100
 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100
 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100
 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100
 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100
 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100
 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100
 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100
 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100
 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100
 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100
 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100
 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100]

In [25]:
valid_predictions = []
valid_labels = []
for cur_row in zip(predictions_oh, labels):
    cur_preds, cur_labels = cur_row
    cur_valid_preds = []
    cur_valid_labels = []
    for p, l in zip(cur_preds, cur_labels):
        if l != -100:
            cur_valid_preds.append(str(p))
            cur_valid_labels.append(str(l))
    valid_predictions.append(' '.join(cur_valid_preds))
    valid_labels.append(' '.join(cur_valid_labels))

dataset_df['true_labels'] = valid_labels
dataset_df['predicted_labels'] = valid_predictions

In [19]:
pd.set_option('display.max_colwidth', None)

In [26]:
dataset_df.head()

,Sentence,NER,true_labels,predicted_labels
0,"Determine whether or not the named entity of type // MISC // is present in the following sentence // SOCCER - JAPAN GET LUCKY WIN , CHINA IN SURPRISE DEFEAT .",-100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 0 0 0 0 0 0 0 0 0 0 0 0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1,"Determine whether or not the named entity of type // ORG // is present in the following sentence // SOCCER - JAPAN GET LUCKY WIN , CHINA IN SURPRISE DEFEAT .",-100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 0 0 0 0 0 0 0 0 0 0 0 0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
2,"Determine whether or not the named entity of type // PER // is present in the following sentence // SOCCER - JAPAN GET LUCKY WIN , CHINA IN SURPRISE DEFEAT .",-100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 0 0 0 0 0 0 0 1 0 0 0 0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
3,"Determine whether or not the named entity of type // LOC // is present in the following sentence // SOCCER - JAPAN GET LUCKY WIN , CHINA IN SURPRISE DEFEAT .",-100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 0 0 1 0 0 0 0 0 0 0 0 0,0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0,0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
4,Determine whether or not the named entity of type // MISC // is present in the following sentence // Nadim Ladki,-100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 -100 0 0,0 0 0 0 0 0 0,0 0 0 0 0 0 0

In [27]:
correct_rows = dataset_df[dataset_df['predicted_labels'] == dataset_df['true_labels']]

print(f"Correct predictions: {len(correct_rows)} / {len(dataset_df)}")

Correct predictions: 13690 / 14732

In [29]:
incorrect_rows = dataset_df[dataset_df['predicted_labels'] != dataset_df['true_labels']]

print(f"Incorrect predictions: {len(incorrect_rows)} / {len(dataset_df)}")

Incorrect predictions: 1042 / 14732

In [35]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")

In [47]:
for row in incorrect_rows.sample(10).itertuples():
    sentence = row.Sentence.split("//")[-1].strip()
    entity_type = row.Sentence.split("//")[-3].strip()
    
    sentence_ids = np.array(tokenizer.encode(sentence))
    true_labels = np.array([int(x) for x in row.true_labels.split()])
    predicted_labels = np.array([int(x) for x in row.predicted_labels.split()])
    
    if len(sentence_ids) != len(true_labels) or len(sentence_ids) != len(predicted_labels):
        print("Length mismatch, skipping...")
        print(f"index: {row.Index}")
        continue
    
    label_indices = true_labels == 1
    predicted_indices = predicted_labels == 1
    label_tokens = tokenizer.decode(sentence_ids[label_indices])
    predicted_tokens = tokenizer.decode(sentence_ids[predicted_indices])
    
    print(f"Index: {row.Index}")
    print(f"Entity Type to find: {entity_type}")
    print(f"Sentence: {sentence}")
    print(f"True Labels: {label_tokens}")
    print(f"Predicted Labels: {predicted_tokens}")
    print("-----")

Index: 4696
Entity Type to find: LOC
Sentence: The longest wait to load on the West Coast was 13 days .
True Labels:
Predicted Labels: West Coast
-----
Index: 6382
Entity Type to find: ORG
Sentence: Wenchang has built a berth for 5,000 deadweight-tonne container ships at the port and invested 34 million yuan ( $ 4.1 million ) to dredge the harbour , Xinhua said .
True Labels: Xinhua
Predicted Labels: Wenchang Xinhua
-----
Index: 9375
Entity Type to find: ORG
Sentence: John Lewis UK store sales up 4.5 % in week .
True Labels: John Lewis UK
Predicted Labels: John Lewis
-----
Index: 14286
Entity Type to find: MISC
Sentence: PACIFIC DIVISION
True Labels:
Predicted Labels: PACIFIC DIVISION
-----
Index: 9752
Entity Type to find: PER
Sentence: Seagramd ace 20/11/96 5,000 Japan
True Labels:
Predicted Labels: Seagramd
-----
Index: 5167
Entity Type to find: LOC
Sentence: Baril said that apart from the group of 150,000 , U.S. and British reconnaissance plans had tracked two much smaller groups of refugees -- one of up to 1,000 north of the town of Masisi and one of up to 8,000 on the road from Bukavu west to Kindu .
True Labels: U.S. Bukavu Kindu
Predicted Labels: U.S. Masisi Bukavu Kindu
-----
Index: 8739
Entity Type to find: MISC
Sentence: ACCESS energy futures prices add to daytime gains .
True Labels: ACCESS
Predicted Labels:
-----
Index: 10650
Entity Type to find: MISC
Sentence: Saturday 's downhill and super G races :
True Labels:
Predicted Labels: G
-----
Index: 13332
Entity Type to find: MISC
Sentence: RUGBY UNION - CAMPESE SIGNS OFF WITH TRY IN WALLABY ROMP .
True Labels:
Predicted Labels: WALLABY ROMP
-----
Index: 9965
Entity Type to find: PER
Sentence: K.T. Arasu
True Labels:
Predicted Labels: K.T. Arasu
-----

# fenerd inference 메모리 문제

16배치 53% -> 1323521~1323536

* 64배치 66% -> 1639424~1639487
* 128배치 66% -> 1639040~1639167
* 192배치 66% -> 1638912~1639103

대략 1639040~1639103 사이에 문제의 장문이 있을 듯

In [8]:
import pandas as pd
import numpy as np

In [2]:
test_set = pd.read_csv("/workspace/datas/fewnerd/supervised/test.switch.csv")

In [ ]:
len_list = list()
for index, row in test_set.iterrows():
    len_list.append(len(row['Sentence'].split()))

print(max(len_list))

318

In [10]:
print(len(test_set) * 0.65)
print(len(test_set) * 0.67)

1615099.2
1664794.56

In [11]:
start_index = 1615099
end_index = 1664794

test_subset = test_set.iloc[start_index:end_index+1]
sub_set_len_list = list()
for index, row in test_subset.iterrows():
    sub_set_len_list.append(len(row['Sentence'].split()))

print(max(sub_set_len_list))

136

In [9]:
np.argmax(len_list)

np.int64(358908)

# 각 데이터셋별 positive 비율

## conll2003

0.05549

## wnut17

0.01374